### ISSUE TITLE
MySQL: Specified key was too long when enabling the module

### ISSUE THREAD

**Issue by lklimek** [dotpay/drupalcommerce#3]
When enabling the module , the following error is displayed:

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes: CREATE TABLE IF NOT EXISTS `dotpay_card_brands` ( `name` varchar(20) DEFAULT NULL, `image` varchar(256) DEFAULT NULL, PRIMARY KEY (`name`), UNIQUE KEY `brand_img` (`image`) ) DEFAULT CHARSET=utf8;; Array ( ) in Dotpay\CardBrand::install() (line 43 of .../dotpay/include/CardBrand.php).

Using version 2.0.2.

It can be also reproduced on simplytest.me - deploy Kickstart 2 and then try to install dotpay module.

My database version: MariaDB 10.1.16-MariaDB

**Comment by tbajorek** [comment]
I hope that now that problem should not exisit.
