### ISSUE TITLE
Duplicate session destroys services in Drupal

### ISSUE THREAD

**Issue by mskrs** [dotpay/drupalcommerce#4]
session_start() in bootstrap.php overwrites default session from Drupal. That causes sometimes users can not login - in my case it had strong collision with Services ( https://www.drupal.org/project/services ), mobile clients were not able to perform any queries after login. Session was closed due to unclear reason.

I think those lines should be removed, because Drupal keeps the session itself.

**Comment by tbajorek** [comment]
We changed that file and now we believe that all will be ok. Please check the new version of this plugin.

**Comment by mskrs** [comment]
Thank you, perfect
